spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root


mybatis:
  typeAliasesPackage: com.demo.entity
#  mapperLocations: classpath:mapper/*.xml
  mapper-locations: classpath:mapper/*.xml